name: Daily Commit

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 03:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update log file - balaji.selvaraj@straive.com
        run: |
          echo "Updated on $(date)" >> update-log.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "balaji.selvaraj@straive.com"
          git add update-log.txt
          git commit -m "Automated daily update - $(date)"
          git push
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}