name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *'  # This runs every day at 12:00 PM UTC

jobs:
  daily_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add a commit with my email
        run: |
          echo "Daily commit by balaji.selvaraj@straive.com" >> daily_commit.txt
          git config --local user.email "balaji.selvaraj@straive.com"
          git config --local user.name "GitHub Action"
          git add daily_commit.txt
          git commit -m "Daily commit by balaji.selvaraj@straive.com" || echo "No changes to commit"